vim.g.mapleader = " "

local map = vim.keymap.set

map("n", "<leader>e", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file tree" })
map("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
map("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Find buffers" })
map("n", "<S-h>", "<cmd>bprevious<CR>", { desc = "Previous buffer" })
map("n", "<S-l>", "<cmd>bnext<CR>", { desc = "Next buffer" })
map("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
map("n", "<C-j>", "<C-w>j", { desc = "Move to lower window" })
map("n", "<C-k>", "<C-w>k", { desc = "Move to upper window" })
map("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })
map("n", "<leader>w", "<cmd>w<CR>", { desc = "Save file" })
map("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit" })
map("v", "<", "<gv", { desc = "Indent left" })
map("v", ">", ">gv", { desc = "Indent right" })
map("n", "<leader>gs", "<cmd>Git<CR>", { desc = "Git status" })
map("n", "<leader>gp", "<cmd>Git push<CR>", { desc = "Git push" })
map("n", "<leader>gc", "<cmd>Git commit<CR>", { desc = "Git commit" })
map("n", "<leader>gl", "<cmd>Git log<CR>", { desc = "Git log" })
map("n", "<leader>gd", "<cmd>Git diff<CR>", { desc = "Git diff" })
map("n", "<leader>tt", "<cmd>ToggleTerm<CR>", { desc = "Toggle terminal" })
map("n", "<leader>ww", "<cmd>VimwikiIndex<CR>", { desc = "Open wiki index" })
map("n", "<leader>wd", "<cmd>VimwikiDiaryIndex<CR>", { desc = "Open wiki diary" })
map("n", "<leader>wy", "<cmd>VimwikiMakeDiaryNote<CR>", { desc = "Today's diary note" })
map("n", "<leader>wt", "<cmd>VimwikiToggleListItem<CR>", { desc = "Toggle checkbox" })
map("n", "<leader>sp", function()
  vim.opt.spell = not vim.opt.spell:get()
  vim.notify("Spell check: " .. tostring(vim.opt.spell:get()))
end, { desc = "Toggle spell check" })
